common_xdg_dirs:
  - "{{ xdg_config_home }}"
  - "{{ xdg_data_home }}"
  - "{{ xdg_cache_home }}"
  - "{{ xdg_state_home }}"
  - "{{ xdg_config_home }}/git" # git role could also own this, but it's benign here
