# ansible/roles/nvim/handlers/main.yml
---

- name: Reload and enable nvim-config timer
  ansible.builtin.systemd:
    name: nvim-config-sync.timer
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  when: ansible_facts['system'] == 'Linux'

- name: Load nvim-config launchd agent
  ansible.builtin.command: >-
    launchctl load -w
    {{ ansible_facts['env']['HOME'] }}/Library/LaunchAgents/com.nvim-config.sync.plist
  changed_when: true
  when: ansible_facts['system'] == 'Darwin'
