#!/usr/bin/env bash
# lazy/disk-encryption.sh — LUKS2 + TPM2 enrollment and passphrase rotation.
# Stub registration for this file is platform-gated in loader.sh (Linux +
# systemd-cryptenroll only) — see the Tier 3 platform-gated block.

# ── LUKS + TPM2 enrollment ─────────────────────────────────────────────────────

# enroll-luks-tpm2
# Discovers LUKS2 partitions and interactively enrolls TPM2 auto-unlock for
# each, one at a time. Before touching any TPM2 slot, guarantees a recovery
# key exists on that device — generating one if missing — so a TPM2 wipe can
# never leave a device with no fallback. TPM2 re-enrollment is scoped to
# `--wipe-slot=tpm2` only; recovery and password slots are never wiped.
#
# Usage:
#   enroll-luks-tpm2
enroll-luks-tpm2() {
    _tpm_require_tools      || return 1
    _tpm_check_tpm2_device  || return 1
    sudo-test                || return 1

    local luks_devices=()
    while IFS= read -r _device; do
        [[ -n "${_device}" ]] && luks_devices+=("${_device}")
    done < <(_tpm_find_luks_devices)

    if [[ ${#luks_devices[@]} -eq 0 ]]; then
        log_error "enroll-luks-tpm2: no LUKS2 partitions found"
        return 1
    fi

    local device_path enrolled_count=0 answer
    for device_path in "${luks_devices[@]}"; do
        echo
        log_info "Found LUKS2 partition: ${device_path}"

        _tpm_ensure_recovery_key "${device_path}" || {
            log_warn "enroll-luks-tpm2: skipping ${device_path} — recovery key not confirmed"
            continue
        }

        _read_prompt "  Register TPM2 for ${device_path}? [y/N]: " answer
        if [[ "$(_str_lower "${answer}")" != "y" ]]; then
            log_info "Skipping TPM2 enrollment for ${device_path}"
            continue
        fi

        # Only ever wipe the tpm2 slot type — recovery/password slots are
        # never touched, no matter what.
        local wipe_flag=()
        if _tpm_has_token_type "${device_path}" "tpm2"; then
            log_info "Existing TPM2 enrollment found for ${device_path} — replacing it"
            wipe_flag=(--wipe-slot=tpm2)
        fi

        if sudo systemd-cryptenroll \
                "${wipe_flag[@]}" \
                --tpm2-device=auto \
                --tpm2-pcrs="0+2+5+7" \
                "${device_path}"; then
            log_info "Successfully enrolled TPM2 for ${device_path}"
            ((enrolled_count++))
        else
            log_error "Failed to enroll TPM2 for ${device_path}"
        fi
    done

    log_info "TPM2 enrollment complete. Enrolled ${enrolled_count} device(s)."
}

# ── LUKS passphrase rotation ───────────────────────────────────────────────────

# rotate-luks-key
# Interactively rotates the passphrase on a LUKS2 device. Prompts for the
# current passphrase and a new one; cryptsetup locates the matching password
# slot itself, so TPM2 and recovery-key slots are never touched. After a
# successful rotation, creates a recovery key only if one is missing — an
# existing recovery key is never wiped or regenerated by this function.
#
# Usage:
#   rotate-luks-key
rotate-luks-key() {
    _tpm_require_tools || return 1
    sudo-test            || return 1

    local luks_devices=()
    while IFS= read -r _device; do
        [[ -n "${_device}" ]] && luks_devices+=("${_device}")
    done < <(_tpm_find_luks_devices)

    if [[ ${#luks_devices[@]} -eq 0 ]]; then
        log_error "rotate-luks-key: no LUKS2 partitions found"
        return 1
    fi

    local device_path answer rotated_count=0
    for device_path in "${luks_devices[@]}"; do
        echo
        log_info "Found LUKS2 partition: ${device_path}"

        _read_prompt "  Rotate the passphrase for ${device_path}? [y/N]: " answer
        if [[ "$(_str_lower "${answer}")" != "y" ]]; then
            log_info "Skipping ${device_path}"
            continue
        fi

        echo
        echo "  You'll be prompted for the CURRENT passphrase, then the new one twice."
        echo "  TPM2 and recovery-key slots on this device are not affected."
        echo

        if sudo cryptsetup luksChangeKey "${device_path}"; then
            log_info "Passphrase rotated for ${device_path}"
            ((rotated_count++))
            _tpm_ensure_recovery_key "${device_path}"
        else
            log_error "Passphrase rotation failed for ${device_path} — no changes made"
        fi
    done

    log_info "Passphrase rotation complete. Rotated ${rotated_count} device(s)."
}

# ── Internal helpers ───────────────────────────────────────────────────────────

_tpm_require_tools() {
    local cmd
    for cmd in cryptsetup blkid systemd-cryptenroll systemctl python3; do
        if ! command -v "${cmd}" &>/dev/null; then
            log_error "disk-encryption: required tool '${cmd}' is not installed"
            return 1
        fi
    done
}

# Uses systemd-cryptenroll's own device enumeration rather than a separate
# tpm2-tools dependency — it's the same backend that will do the enrolling.
_tpm_check_tpm2_device() {
    local tpm2_list
    tpm2_list="$(systemd-cryptenroll --tpm2-device=list 2>/dev/null)"
    if [[ -z "${tpm2_list}" ]] || ! echo "${tpm2_list}" | grep -q '/dev/tpm'; then
        log_error "enroll-luks-tpm2: no usable TPM2 device found"
        return 1
    fi
}

# Prints every LUKS2 partition path, one per line, via blkid rather than
# lsblk tree-parsing — finds locked and unlocked devices alike. LUKS1
# partitions are detected but skipped with a warning (systemd-cryptenroll
# and this module's rotation flow both target LUKS2 only).
_tpm_find_luks_devices() {
    local dev
    while IFS= read -r dev; do
        [[ -z "${dev}" ]] && continue
        if sudo cryptsetup isLuks --type luks2 "${dev}" 2>/dev/null; then
            echo "${dev}"
        elif sudo cryptsetup isLuks "${dev}" 2>/dev/null; then
            log_warn "disk-encryption: ${dev} is LUKS1 — this module targets LUKS2 only, skipping" >&2
        fi
    done < <(sudo blkid -t TYPE=crypto_LUKS -o device 2>/dev/null)
}

# _tpm_has_token_type <device> <recovery|tpm2|password>
_tpm_has_token_type() {
    local device_path="$1" token_type="$2" listing
    listing="$(sudo systemd-cryptenroll "${device_path}" 2>/dev/null)"
    echo "${listing}" | awk 'NR>1{print $2}' | grep -qx "${token_type}"
}

# Ensures a recovery key exists on the device. Only ever creates one when
# missing — never wipes or regenerates an existing recovery key. No
# --wipe-slot is ever used here, so other existing slots are untouched.
_tpm_ensure_recovery_key() {
    local device_path="$1"

    if _tpm_has_token_type "${device_path}" "recovery"; then
        log_info "disk-encryption: recovery key already enrolled for ${device_path}"
        return 0
    fi

    log_warn "disk-encryption: no recovery key found for ${device_path} — creating one now"
    echo
    echo "  You'll be prompted for the disk's existing passphrase. A new recovery"
    echo "  key will then be generated and printed below — store it somewhere safe."
    echo

    # Capture via Python's stdlib pty module rather than script(1) — script
    # is part of the full util-linux package, which Fedora now splits out of
    # the default install (util-linux-core only). python3 is already a hard
    # dependency here, and pty/os are stdlib, so this needs nothing extra.
    # pty.fork() gives the child a real controlling terminal, so echo
    # suppression and password-prompt handling behave exactly as if run
    # directly — no bare-pipe weirdness like the previous approach had.
    local temp_dir transcript_file
    if [[ -d /dev/shm && -w /dev/shm ]]; then
        temp_dir="/dev/shm"
    else
        temp_dir="${TMPDIR:-/tmp}"
    fi
    transcript_file="$(mktemp "${temp_dir}/tpm-recovery.XXXXXX")"
    chmod 600 "${transcript_file}"

    python3 "${SHELL_CONFIG_DIR}/workers/disk-encryption-pty-capture.py" "${transcript_file}" \
        sudo systemd-cryptenroll --recovery-key "${device_path}"

    local recovery_transcript
    recovery_transcript="$(_tpm_clean_transcript < "${transcript_file}")"
    shred -u "${transcript_file}" 2>/dev/null || rm -f "${transcript_file}"

    # Verify by re-checking device state rather than trusting an exit code
    # (bash $PIPESTATUS and zsh $pipestatus aren't the same mechanism, and
    # pty.spawn()'s return value is a raw wait-status, not a plain exit code).
    if ! _tpm_has_token_type "${device_path}" "recovery"; then
        log_error "disk-encryption: recovery key enrollment did not succeed for ${device_path}"
        unset recovery_transcript
        return 1
    fi

    _tpm_offer_secret_storage "${device_path}" "${recovery_transcript}"
    unset recovery_transcript
}

# Strips ANSI escape sequences and carriage returns from a script(1)
# typescript so a captured transcript reads cleanly when stored as a note.
_tpm_clean_transcript() {
    sed $'s/\x1b\[[0-9;]*[a-zA-Z]//g' | tr -d '\r'
}

# Offers to store the just-generated recovery key transcript in whichever of
# Bitwarden/1Password is installed and unlocked. Declines silently if neither
# is available — the key was already shown above either way.
_tpm_offer_secret_storage() {
    local device_path="$1" transcript="$2"
    local title
    title="LUKS Recovery Key — $(hostname -s 2>/dev/null || echo unknown) — ${device_path}"
    local have_bw=false have_op=false answer

    command -v bw &>/dev/null && [[ "$(_tpm_bw_status)" == "unlocked" ]] && have_bw=true
    command -v op &>/dev/null && op whoami &>/dev/null 2>&1 && have_op=true

    if [[ "${have_bw}" != "true" && "${have_op}" != "true" ]]; then
        log_info "disk-encryption: Bitwarden/1Password not available or unlocked — recovery key was only shown above"
        return 0
    fi

    if [[ "${have_bw}" == "true" ]]; then
        _read_prompt "  Save this recovery key to Bitwarden as a secure note? [y/N]: " answer
        [[ "$(_str_lower "${answer}")" == "y" ]] && _tpm_bw_store_recovery "${title}" "${transcript}"
    fi
    if [[ "${have_op}" == "true" ]]; then
        _read_prompt "  Save this recovery key to 1Password as a secure note? [y/N]: " answer
        [[ "$(_str_lower "${answer}")" == "y" ]] && _tpm_op_store_recovery "${title}" "${transcript}"
    fi
}

_tpm_bw_status() {
    [[ -z "${BW_SESSION:-}" ]] && return 0
    bw status 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin).get("status",""))' 2>/dev/null
}

_tpm_bw_store_recovery() {
    local title="$1" body="$2" item_json encoded
    item_json="$(bw get template item 2>/dev/null | python3 -c '
import json, sys
tpl = json.load(sys.stdin)
tpl["type"] = 2
tpl["name"] = sys.argv[1]
tpl["secureNote"] = {"type": 0}
tpl["notes"] = sys.argv[2]
print(json.dumps(tpl))
' "${title}" "${body}")"

    if [[ -z "${item_json}" ]]; then
        log_error "disk-encryption: failed to build Bitwarden item"
        return 1
    fi

    encoded="$(echo "${item_json}" | bw encode)"
    if bw create item "${encoded}" >/dev/null 2>&1; then
        log_info "disk-encryption: recovery key stored in Bitwarden as '${title}'"
    else
        log_error "disk-encryption: failed to create Bitwarden item '${title}'"
        return 1
    fi
}

_tpm_op_store_recovery() {
    local title="$1" body="$2"
    if op item create --category "Secure Note" --title "${title}" "notesPlain=${body}" >/dev/null 2>&1; then
        log_info "disk-encryption: recovery key stored in 1Password as '${title}'"
    else
        log_error "disk-encryption: failed to create 1Password item '${title}'"
        return 1
    fi
}